name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Set deine gewünschte Go-Version hier ein

    # Cache dependencies
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Run tests
    - name: Run tests
      run: go test ./... -v

    # Build the project
    - name: Build
      run: go build -o bin/myapp ./...

    # Upload the build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-go-app
        path: bin/myapp

